// <auto-generated />
using System;
using InventoryStock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryStock.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209131906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryStock.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastRestocked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            LastRestocked = new DateTime(2026, 1, 30, 18, 49, 5, 212, DateTimeKind.Local).AddTicks(8466),
                            Name = "Laptop",
                            Price = 1200m,
                            StockCount = 5
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            LastRestocked = new DateTime(2026, 2, 7, 18, 49, 5, 212, DateTimeKind.Local).AddTicks(8481),
                            Name = "Mouse",
                            Price = 25m,
                            StockCount = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            LastRestocked = new DateTime(2026, 1, 25, 18, 49, 5, 212, DateTimeKind.Local).AddTicks(8486),
                            Name = "Monitor",
                            Price = 300m,
                            StockCount = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
